import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {EventEmitter} from 'node:events';
import {Vec3} from 'vec3';
import registryLoader from 'prismarine-registry';
import blockLoader from 'prismarine-block';
import pf from 'mineflayer-pathfinder';
import {StarterScoutGoal} from '../src/actions.js';
import {planReturnablePath,STARTER_AVOID_BLOCK_NAMES} from '../src/navigation-guards.js';
import {retainedLeafAnchor} from '../src/construction-guards.js';
test('saved canopy has a certified starter landing adjacent to an unreachable exact column',async()=>{
 const f=JSON.parse(readFileSync(new URL('./fixtures/scout-924-landing.json',import.meta.url)));
 const registry=registryLoader(f.minecraftVersion),Block=blockLoader(registry),cells=new Map(f.cells.map(([x,y,z,state])=>[[x,y,z].join(','),state]));
 let unknown=0;
 const blockAt=p=>{p=p.floored();const state=cells.get(p.toArray().join(','));if(state===undefined||state===null){unknown++;return null}const block=Block.fromStateId(state,0);block.position=p;return block};
 const home=new Vec3(...f.home),bot=Object.assign(new EventEmitter(),{registry,blockAt,entity:{position:new Vec3(...f.origin),onGround:f.onGround,velocity:new Vec3(0,0,0),effects:{}},entities:{},inventory:{items:()=>[]},game:{minY:-64,height:384,dimension:f.dimension},clearControlStates(){}});
 for(const e of f.recordedEntityInputs)bot.entities[e.id]={...e,position:new Vec3(e.position.x,e.position.y,e.position.z)};
 pf.pathfinder(bot);const moves=new pf.Movements(bot);
 Object.assign(moves,{canDig:false,allow1by1towers:false,allowParkour:false,scafoldingBlocks:[],maxDropDown:3});
 moves.exclusionAreasStep.push(b=>b.position&&b.position.distanceTo(home)<=256?0:1000,b=>b.isWaterlogged?1000:0);
 for(const name of STARTER_AVOID_BLOCK_NAMES)if(registry.blocksByName[name])moves.blocksToAvoid.add(registry.blocksByName[name].id);
 bot.pathfinder.setMovements(moves);
 const allowed=p=>new Vec3(p.x,p.y,p.z).distanceTo(home)<=256&&new Vec3(p.x+.5,p.y,p.z+.5).distanceTo(home)<=256;
 const origin=new pf.goals.GoalNear(...f.query.returnGoal),target=new Vec3(f.query.nominalGoal[0],f.origin[1],f.query.nominalGoal[1]);
 await assert.rejects(planReturnablePath(bot,moves,new pf.goals.GoalXZ(target.x,target.z),origin,{planningBudget:1600,validateNode:allowed}),/noPath/);
 assert.equal(unknown,0);
 const plan=await planReturnablePath(bot,moves,new StarterScoutGoal(target,allowed),origin,{planningBudget:1600,validateNode:allowed});
 assert.deepEqual(plan.endpoint.toArray(),f.expected.nearEndpoint);assert.equal(plan.forwardNodes,9);assert.equal(plan.reverseNodes,8);
 for(const {support,proof} of f.leafProofs)assert.deepEqual(retainedLeafAnchor(blockAt,new Vec3(...support)),proof);
 assert.equal(unknown,0);assert.deepEqual(bot.entity.position.toArray(),f.origin);
});
