'use strict';
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if(document.querySelector('#demoSteps')) {
const demos={starter:{cmd:'survive starter',status:'ILLUSTRATED STARTER SEQUENCE',steps:['Observe nearby trees and safe terrain','Gather wood and verify item pickups','Craft tools at a verified crafting table','Collect stone and craft the starter kit','Return home • or pause with a clear reason']},follow:{cmd:'follow me',status:'ILLUSTRATED FOLLOW SEQUENCE',steps:['Identify the configured visible owner','Plan a reachable route toward the player','Follow for a bounded period','Observe progress and changing terrain','Stop if interrupted or the route fails']},stop:{cmd:'stop',status:'ILLUSTRATED INTERRUPT SEQUENCE',steps:['Request cancellation of the current action','Release active movement controls','Allow in-flight inventory work to settle','Keep the starter job paused','Resume only when you explicitly ask']}};
let demo='starter';function renderDemo(key){demo=key;const d=demos[key];document.querySelector('#demoCommand').textContent=d.cmd;document.querySelector('#demoStatus').textContent=d.status;const root=document.querySelector('#demoSteps');root.replaceChildren();d.steps.forEach((text,i)=>{const row=document.createElement('div');row.className='step';row.style.animationDelay=reduced?'0s':`${i*.1}s`;const icon=document.createElement('span');icon.textContent=String(i+1).padStart(2,'0');const label=document.createElement('div');label.textContent=text;row.append(icon,label);root.append(row)});document.querySelectorAll('[data-demo]').forEach(b=>{const on=b.dataset.demo===key;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))})}document.querySelectorAll('[data-demo]').forEach(b=>b.addEventListener('click',()=>renderDemo(b.dataset.demo)));document.querySelector('#replay').addEventListener('click',()=>renderDemo(demo));renderDemo('starter');
}
if(document.querySelector('#benchRows')) {
const scores=[['MineLine','Prepared mining and pickup','3 / 3','3 / 3','skills'],['Workbench','Supplied-ingredient crafting','6 / 6','6 / 6','skills'],['Pathfinder','Prepared movement routes','2 / 2','2 / 2','skills'],['CommandSense','Local command grammar','12 / 14','14 / 14','skills'],['SafetyLatch','Simulated control failures','6 / 6','6 / 6','skills'],['Trailhead','Fresh-world starter and return','0 / 3*','0 / 3','autonomy'],['GoalSense LLM','Live language planning','Not run','Not run','autonomy']];function renderScores(view){const root=document.querySelector('#benchRows');root.replaceChildren();for(const [name,desc,a,b,group] of scores){if(view!=='all'&&view!==group)continue;const tr=document.createElement('tr');const label=document.createElement('td');const title=document.createElement('strong');title.textContent=name;const sub=document.createElement('small');sub.textContent=desc;label.append(title,sub);const left=document.createElement('td');left.textContent=a;if(name==='Trailhead'){const small=document.createElement('small');small.textContent='* Mode absent';left.append(small)}const right=document.createElement('td');right.textContent=b;if(group==='skills'){right.className='best';if(a===b)left.className='best'}tr.append(label,left,right);root.append(tr)}document.querySelectorAll('[data-view]').forEach(x=>{const on=x.dataset.view===view;x.classList.toggle('active',on);x.setAttribute('aria-pressed',String(on))})}document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>renderScores(b.dataset.view)));renderScores('all');
}
if(document.querySelector('#copy')) document.querySelector('#copy').addEventListener('click',async()=>{const b=document.querySelector('#copy');try{await navigator.clipboard.writeText(document.querySelector('#installCode').textContent);b.textContent='Copied ✓';setTimeout(()=>{b.textContent='Copy commands'},2200)}catch{b.textContent='Select commands below';const r=document.createRange();r.selectNodeContents(document.querySelector('#installCode'));const s=window.getSelection();s.removeAllRanges();s.addRange(r)}});
if(document.querySelector('#world')) {
const canvas=document.querySelector('#world'),ctx=canvas.getContext('2d');let paused=reduced,raf=0,start=performance.now();const motion=document.querySelector('#motion');function motionLabel(){motion.textContent=paused?'Play animation ▷':'Pause animation Ⅱ';motion.setAttribute('aria-pressed',String(paused))}motionLabel();motion.addEventListener('click',()=>{paused=!paused;motionLabel();if(!paused&&!raf)raf=requestAnimationFrame(frame);else if(paused){cancelAnimationFrame(raf);raf=0;draw(0)}});
function poly(points,color){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fillStyle=color;ctx.fill()}
let scale=1,ox=0,oy=0;function iso(x,z,y=0){return[ox+(x-z)*25*scale,oy+(x+z)*12.5*scale-y*25*scale]}
function cube(x,z,y,w=1,d=1,h=1,c=['#a4bc6d','#6a8351','#7d975c']){const a=iso(x,z,y+h),b=iso(x+w,z,y+h),cc=iso(x+w,z+d,y+h),dd=iso(x,z+d,y+h),e=iso(x,z,y),f=iso(x+w,z,y),g=iso(x+w,z+d,y),hh=iso(x,z+d,y);poly([dd,cc,g,hh],c[1]);poly([b,cc,g,f],c[2]);poly([a,b,cc,dd],c[0])}
function tree(x,z,size=1){cube(x+.36,z+.36,1,.35,.35,1.6*size,['#9d7752','#614d37','#7b6041']);cube(x-.22,z-.22,2.2*size,1.55,1.55,.8,['#8fa961','#496f43','#63834e']);cube(x+.05,z+.05,3*size,1,1,.65,['#b0c37b','#6c8b50','#839e5f'])}
function draw(t){const r=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*dpr)||canvas.height!==Math.round(r.height*dpr)){canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);scale=Math.min(r.width/530,r.height/570);ox=r.width/2;oy=r.height*.40+Math.sin(t*.5)*3*scale;
ctx.save();ctx.translate(r.width/2,r.height*.73);ctx.scale(1,.28);ctx.beginPath();ctx.ellipse(0,0,180*scale,100*scale,0,0,Math.PI*2);ctx.fillStyle='#536c2920';ctx.fill();ctx.restore();
for(let sum=-6;sum<=8;sum++)for(let x=-4;x<=4;x++){let z=sum-x;if(z< -3||z>4)continue;if((x===-4||x===4)&&(z===-3||z===4))continue;const edge=x===4||z===4;cube(x,z,-.7,1,1,1.7,[(x+z)%3===0?'#adbf7a':'#9fb66b',edge?'#987151':'#876a48','#a57e58']);if((x*7+z*3)%5===0)cube(x+.22,z+.1,1,.35,.22,.04,['#bace86','#9bb361','#a8bf71'])}
tree(-3,-2);tree(-1.4,-2.7,.85);tree(2.5,-2.1,1.1);
// Cabin built from explicit voxel shapes.
cube(-2.7,.3,1,2,1.8,1.5,['#d9b57d','#a77749','#c18d57']);cube(-2.9,.1,2.5,2.4,2.2,.3,['#627352','#374e38','#486142']);cube(-2.6,.4,2.8,1.8,1.6,.3,['#71805a','#40553a','#526849']);cube(-2.25,.7,3.1,1.1,1,.3,['#829463','#4b6141','#62764d']);cube(-1.1,1.5,1,.08,.52,1.1,['#5c4b38','#69513c','#4c3d2d']);cube(-2.5,2.105,1.8,.55,.03,.45,['#f5dc8e','#f5dc8e','#f5dc8e']);
// Stone outcrop and a crafting block.
cube(2.1,.1,1,1.2,1.2,.65,['#b6bcb2','#777e78','#90988d']);cube(2.4,.3,1.65,.6,.7,.5,['#c7ccc0','#8b9388','#a3ab9c']);cube(.9,2.6,1,.75,.75,.75,['#caa06a','#875d3b','#aa774a']);for(let i=0;i<3;i++)for(let j=0;j<3;j++)cube(.96+i*.21,2.66+j*.21,1.75,.15,.15,.012,['#795333','#795333','#795333']);
// Friendly original robot, not an official Minecraft skin.
const bx=.15+Math.sin(t*.4)*.35,bz=1.45,hop=Math.max(0,Math.sin(t*2))*.05;cube(bx-.23,bz,1,.21,.25,.38,['#455a47','#263d30','#344b38']);cube(bx+.15,bz,1,.21,.25,.38,['#455a47','#263d30','#344b38']);cube(bx-.35,bz-.1,1.36+hop,.82,.48,.65,['#d1ed78','#86a74a','#adca60']);cube(bx-.53,bz-.05,1.45+hop,.18,.3,.48,['#e0f495','#809b46','#a3bf5e']);cube(bx+.49,bz-.05,1.45+hop,.18,.3,.48,['#e0f495','#809b46','#a3bf5e']);cube(bx-.42,bz-.12,2+hop,.96,.61,.69,['#e1f39a','#a3bf5d','#bdd67b']);cube(bx-.25,bz+.497,2.23+hop,.16,.02,.18,['#183b2d','#183b2d','#183b2d']);cube(bx+.17,bz+.497,2.23+hop,.16,.02,.18,['#183b2d','#183b2d','#183b2d']);cube(bx+.05,bz+.13,2.69+hop,.05,.05,.28,['#455e37','#455e37','#455e37']);cube(bx-.025,bz+.055,2.97+hop,.2,.2,.16,['#f4b078','#c16a42','#df8b53']);
// Floating field markers.
for(let i=0;i<5;i++){const a=t*.3+i*1.9;const x=r.width*.5+Math.sin(a)*r.width*.35,y=r.height*.3+Math.cos(a*.7+i)*r.height*.17;ctx.fillStyle=i%2?'#ffffff88':'#8aab5955';ctx.fillRect(x,y,4*scale,4*scale)}
}
function frame(now){draw((now-start)/1000);raf=paused?0:requestAnimationFrame(frame)}new ResizeObserver(()=>draw(paused?0:(performance.now()-start)/1000)).observe(canvas);draw(0);if(!paused)raf=requestAnimationFrame(frame);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0}else if(!paused&&!raf)raf=requestAnimationFrame(frame)});

}

const downloadButton=document.querySelector('#downloadBroBot');if(downloadButton)downloadButton.addEventListener('click',()=>{const thanks=document.querySelector('#downloadThanks');thanks.hidden=false;thanks.focus({preventScroll:true});thanks.scrollIntoView({behavior:reduced?'instant':'smooth',block:'center'});});

const commandGuide=[["collect 4 oak logs", "Gathering", "A supported offline phrase: collect up to four reachable oak logs. No JSON or API key needed.", "Direct \u00b7 no key"], ["craft a furnace", "Crafting", "A supported offline phrase using owned ingredients and a usable crafting table.", "Direct \u00b7 no key"], ["status", "Basics", "See connection, current action and starter status.", "Direct \u00b7 no key"], ["inventory", "Basics", "Check the materials BroBot actually carries.", "Direct \u00b7 no key"], ["stop", "Safety", "Interrupt active work. Wait for in-flight actions to settle.", "Direct \u00b7 no key"], ["follow me", "Movement", "Follow your configured player for up to one minute.", "Direct \u00b7 no key"], ["come here", "Movement", "Walk toward your visible player.", "Direct \u00b7 no key"], ["remember home", "Movement", "Save the bot\u2019s current position as home.", "Direct \u00b7 no key"], ["home", "Movement", "Return to the saved home waypoint.", "Direct \u00b7 no key"], ["goto 20 64 10", "Movement", "Walk to explicit world coordinates when a route is available.", "Direct \u00b7 no key"], ["survive starter", "Starter", "Start the bounded wood \u2192 tools \u2192 furnace \u2192 home job.", "Offline controller"], ["survive resume", "Starter", "Resume a paused or blocked starter job after reviewing the problem.", "Offline controller"], ["action collect {\"block\":\"oak_log\",\"count\":4,\"radius\":24}", "Gathering", "Mine up to four reachable oak logs and verify the pickups.", "Direct \u00b7 no key"], ["action craft {\"item\":\"stone_pickaxe\",\"count\":1}", "Crafting", "Craft one stone pickaxe from owned ingredients.", "Direct \u00b7 no key"], ["action craft {\"item\":\"furnace\",\"count\":1}", "Crafting", "Craft a furnace when you have the required cobblestone.", "Direct \u00b7 no key"], ["action pickup {\"radius\":8}", "Gathering", "Attempt to collect reachable nearby item drops.", "Direct \u00b7 no key"], ["action eat {\"item\":\"bread\"}", "Safety", "Eat carried bread when the food bar is not full.", "Direct \u00b7 no key"], ["goal Collect four oak logs", "AI planner", "Ask the optional model to plan actions toward a goal. Requires a configured API key and uses paid API calls.", "Paid API required"]];
if(document.querySelector('#commandCards')){let selectedCategory='All';const search=document.querySelector('#commandSearch');function renderCommands(){const query=search.value.toLowerCase().trim();const root=document.querySelector('#commandCards');root.replaceChildren();const matches=commandGuide.filter(c=>(selectedCategory==='All'||c[1]===selectedCategory)&&c.join(' ').toLowerCase().includes(query));for(const [command,category,description,mode]of matches){const card=document.createElement('article');card.className='command-card';const tag=document.createElement('span');tag.className='eyebrow';tag.textContent=category+' / '+mode;const code=document.createElement('code');code.textContent=command;const paragraph=document.createElement('p');paragraph.textContent=description;const copy=document.createElement('button');copy.className='copy-command';copy.textContent='Copy command';copy.setAttribute('aria-label','Copy '+command);copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(command);copy.textContent='Copied ✓';}catch{copy.textContent='Select the command to copy';}});card.append(tag,code,paragraph,copy);root.append(card);}document.querySelector('#commandCount').textContent=matches.length?matches.length+' commands ready to explore':'No matches. Try a different word or category.';document.querySelectorAll('[data-category]').forEach(button=>{const active=button.dataset.category===selectedCategory;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});}search.addEventListener('input',renderCommands);document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{selectedCategory=button.dataset.category;renderCommands();}));renderCommands();}
