const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(require('node:path').join(__dirname,'../evidence.js'),'utf8');
function fixture(fetch){const element=()=>({textContent:'',value:'',className:'',children:[],handlers:{},attrs:{},append(...e){this.children.push(...e)},replaceChildren(...e){this.children=e},addEventListener(e,f){this.handlers[e]=f},setAttribute(k,v){this.attrs[k]=v}});const ids=Object.fromEntries(['worldCases','worldStatus','worldSource','worldFilter','worldSearch','worldShown','worldReset'].map(k=>['#'+k,element()]));ids['#worldFilter'].value='all';const buttons=['core','additional','firstPass','fresh'].map(cohort=>Object.assign(element(),{dataset:{cohort}}));const panel={querySelector:k=>ids[k],querySelectorAll:()=>buttons};vm.runInNewContext(source,{document:{querySelector:()=>panel,createElement:element},fetch});return{ids,buttons};}
const pass=seed=>({seed,status:'passed',passed:true,elapsedMs:123456,reason:'Completed'});
const fail=seed=>({seed,status:'failed',passed:false,elapsedMs:300000,reason:'Timeout'});
const data={sourceCommit:'a'.repeat(40),minecraft:'1.21.8',groups:{core:{passed:1,scheduled:3,label:'Original development worlds',cases:[pass('42'),fail('1'),{seed:'2',status:'not_run',passed:false,elapsedMs:null,reason:'Not run'}]},additional:{passed:0,scheduled:1,label:'Additional development worlds',cases:[fail('7')]},firstPass:{passed:1,scheduled:2,label:'New first-pass worlds',note:'Selected before inspection',cases:[pass('8'),fail('9')]}}};
data.groups.fresh={passed:1,scheduled:2,label:'Preselected first-pass worlds',note:'All failures retained',sourceCommit:'b'.repeat(40),cases:[pass('10'),fail('11')]};
const settle=()=>new Promise(r=>setImmediate(r));
test('all four cohorts retain failed and unrun cases, denominator, timing and selection note',async()=>{const f=fixture(async()=>({ok:true,json:async()=>data}));await settle();assert.match(f.ids['#worldStatus'].textContent,/1\/2.*All failures retained/);assert.match(f.ids['#worldSource'].textContent,/bbbbbbb/);f.buttons[0].handlers.click();assert.match(f.ids['#worldSource'].textContent,/aaaaaaa/);assert.match(f.ids['#worldStatus'].textContent,/1\/3/);assert.equal(f.ids['#worldCases'].children.length,3);assert.equal(f.ids['#worldCases'].children[2].children[0].children[1].textContent,'Not run');assert.equal(f.ids['#worldCases'].children[0].children[1].textContent,'123.5 seconds');f.buttons[1].handlers.click();assert.match(f.ids['#worldStatus'].textContent,/0\/1/);assert.equal(f.ids['#worldCases'].children[0].children[0].children[1].textContent,'Stopped');f.buttons[2].handlers.click();assert.match(f.ids['#worldStatus'].textContent,/1\/2.*Selected before inspection/);assert.equal(f.buttons[2].attrs['aria-pressed'],'true');assert.equal(f.buttons[1].attrs['aria-pressed'],'false');});
test('failed data loading has an explicit fallback instead of invented scores',async()=>{const f=fixture(async()=>({ok:false}));await settle();assert.match(f.ids['#worldStatus'].textContent,/could not load/);assert.equal(f.ids['#worldCases'].children.length,0);});
test('inconsistent scores, missing cases, duplicate seeds and bad timings fail closed',async()=>{for(const mutate of [d=>d.groups.core.passed=3,d=>d.groups.core.cases.pop(),d=>d.groups.core.cases[1].seed='42',d=>d.groups.core.cases[0].elapsedMs=-1,d=>d.groups.core.cases[0].passed=false,d=>delete d.groups.firstPass,d=>d.groups.fresh.sourceCommit='bad']){const broken=structuredClone(data);mutate(broken);const f=fixture(async()=>({ok:true,json:async()=>broken}));await settle();assert.match(f.ids['#worldStatus'].textContent,/could not load/);assert.equal(f.ids['#worldCases'].children.length,0);}});

test('seed and outcome filters keep the full denominator, combine, and clear without hiding failures by default',async()=>{const f=fixture(async()=>({ok:true,json:async()=>data}));await settle();assert.equal(f.ids['#worldCases'].children.length,2);f.ids['#worldFilter'].value='failed';f.ids['#worldFilter'].handlers.change();assert.equal(f.ids['#worldCases'].children.length,1);assert.match(f.ids['#worldShown'].textContent,/Showing 1 of 2/);assert.match(f.ids['#worldStatus'].textContent,/1\/2/);f.ids['#worldSearch'].value='10';f.ids['#worldSearch'].handlers.input();assert.match(f.ids['#worldCases'].children[0].textContent,/No runs match/);f.ids['#worldReset'].handlers.click();assert.equal(f.ids['#worldSearch'].value,'');assert.equal(f.ids['#worldFilter'].value,'all');assert.equal(f.ids['#worldCases'].children.length,2);f.ids['#worldSearch'].value='11';f.ids['#worldSearch'].handlers.input();assert.equal(f.ids['#worldCases'].children[0].children[0].children[0].textContent,'World 11');});
