const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(require('node:path').join(__dirname,'../telemetry.js'),'utf8');
const data=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'../run-telemetry.json'),'utf8'));
function fixture(fetcher){const element=()=>({textContent:'',value:'0',disabled:true,children:[],handlers:{},attrs:{},append(...nodes){this.children.push(...nodes)},replaceChildren(...nodes){this.children=nodes},setAttribute(k,v){this.attrs[k]=v},addEventListener(k,v){this.handlers[k]=v}});const ids=Object.fromEntries(['traceMap','traceSlider','tracePlay','traceReset','traceTime','traceAction','traceVitals','tracePosition','traceInventory','traceSource'].map(k=>['#'+k,element()]));let tick=null,intervals=0;const doc={hidden:false,handlers:{},querySelector:()=>({querySelector:k=>ids[k]}),createElement:element,createElementNS:element,addEventListener(k,v){this.handlers[k]=v}};vm.runInNewContext(source,{document:doc,fetch:fetcher??(async()=>({ok:true,json:async()=>data})),setInterval(fn){tick=fn;return ++intervals},clearInterval(){tick=null}});return{ids,doc,tick:()=>tick?.(),active:()=>tick!==null,intervals:()=>intervals};}
const settle=()=>new Promise(r=>setImmediate(r));
test('recorded telemetry starts paused and scrubbing shows the actual verified finish',async()=>{const f=fixture();await settle();assert.equal(f.active(),false);assert.equal(f.ids['#tracePlay'].disabled,false);assert.match(f.ids['#traceInventory'].children[0].textContent,/Empty inventory/);f.ids['#traceSlider'].value=String(data.samples.length-1);f.ids['#traceSlider'].handlers.input();assert.equal(f.ids['#traceAction'].textContent,'complete');assert.ok(f.ids['#traceInventory'].children.some(c=>c.textContent.includes('stone pickaxe')));assert.ok(f.ids['#traceInventory'].children.some(c=>c.textContent.includes('furnace')));assert.equal(f.active(),false);});
test('repeated play, pause, reset, completion and hiding release the replay timer',async()=>{const f=fixture();await settle();f.ids['#tracePlay'].handlers.click();assert.equal(f.active(),true);f.tick();f.ids['#tracePlay'].handlers.click();assert.equal(f.active(),false);f.ids['#tracePlay'].handlers.click();f.doc.hidden=true;f.doc.handlers.visibilitychange();assert.equal(f.active(),false);f.ids['#traceReset'].handlers.click();assert.equal(f.ids['#traceSlider'].value,'0');f.doc.hidden=false;f.ids['#tracePlay'].handlers.click();for(let i=0;i<data.samples.length+1;i++)f.tick();assert.equal(f.active(),false);assert.equal(f.ids['#traceAction'].textContent,'complete');f.ids['#tracePlay'].handlers.click();assert.equal(f.ids['#traceSlider'].value,'0');});
test('missing telemetry keeps controls disabled and shows a useful fallback',async()=>{const f=fixture(async()=>({ok:false}));await settle();assert.equal(f.ids['#tracePlay'].disabled,true);assert.match(f.ids['#traceSource'].textContent,/could not load/);});
test('malformed or incomplete run records never enable replay controls',async()=>{for(const mutate of [d=>delete d.home,d=>delete d.samples[1].inventory,d=>d.samples[1].seconds=0,d=>d.samples.at(-1).action='collect',d=>d.samples.at(-1).inventory=[],d=>d.samples.at(-1).position.x+=100,d=>d.sourceCommit='unknown']){const broken=structuredClone(data);mutate(broken);const f=fixture(async()=>({ok:true,json:async()=>broken}));await settle();assert.equal(f.ids['#tracePlay'].disabled,true);assert.equal(f.ids['#traceSlider'].disabled,true);assert.match(f.ids['#traceSource'].textContent,/could not load/);}});
